### ISSUE TITLE
Allow to address an ALSA subdevice

### ISSUE THREAD

**Issue by jonaseberle** [BlokasLabs/amidiauto#2]
In such a setup:
<pre>
$ amidi -l
       IO  hw:5,0,0  minilogue MIDI 1
       IO  hw:5,0,1  minilogue MIDI 2
</pre>
it is currently not possible to address the second hardware port/subdevice (I am unsure about the naming).
Currently the device can only be matched against the string "minilogue".

What could we do about it? 
Should we allow a "minilogue MIDI 2" syntax (as output by `amidi -l` and `aconnect -l`) in `amidiauto.conf` and build such a string here https://github.com/BlokasLabs/amidiauto/blob/master/amidiauto.cpp#L142
Or would it be easier to allow a "minilogue:1" syntax?

**Comment by woollybird** [comment]
Hi there,

I am facing the same behavior with amidiauto. I am using a controller which have x4 MIDI outputs and only the first is addressed (auto-connected) by the service.

```sh
$ amidi -l
     Dir Device    Name
     IO  hw:3,0,0  Ilophone MIDI 1
     IO  hw:3,0,1  Ilophone MIDI 2
     IO  hw:3,0,2  Ilophone MIDI 3
     IO  hw:3,0,3  Ilophone MIDI 4
```

![Capture d’écran 2021-11-02 à 18 50 01](https://user-images.githubusercontent.com/34857582/139919091-8aa8e5ed-ec6d-4976-ab28-593de384fdcd.png)

@jonaseberle  did you find a solution to this ?

It would be great that next releases of amidiauto auto address all ports of MIDI devices.

Best.

**Comment by gtrainavicius** [comment]
I'd recommend using amidiminder - https://community.blokas.io/t/amidiminder-utility/2243, it was inspired by amidiauto and can handle multiport devices. :)

**Comment by jonaseberle** [comment]
I've since changed my setup a bit and haven't come across this limitation any more. 
I haven't tried https://github.com/mzero/amidiminder but it seems to tackle this issue.

**Comment by woollybird** [comment]
@gtrainavicius That works for me by editing the /etc/amidiminder.rules file :

```shell
"Ilophone":* <-x- *
  # Do not connect anything to Ilophone.

"Ilophone":1 --> "Pure Data":1
  # Connect Ilophone port #2 to Pure Data port #2
```

However that's not an automatic feature as I had expected. Thanks for the tip @gtrainavicius 👍

**Comment by jonaseberle** [comment]
I think this can be closed in favor of https://github.com/mzero/amidiminder
