### ISSUE TITLE
is it possible to connect devices with multiple midi ports

### ISSUE THREAD

**Issue by battlemaul** [BlokasLabs/amidiauto#5]
I have at problem getting amidiauto to map devices with multiple midi ports.
It looks like it only maps the first port (port 0) of the device

client 0: 'System' [type=kernel]
    0 'Timer           '
    1 'Announce        '
        Connecting To: 128:0
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 28: 'Virtual Raw MIDI 3-0' [type=kernel,card=3]
    0 'VirMIDI 3-0     '
client 29: 'Virtual Raw MIDI 3-1' [type=kernel,card=3]
    0 'VirMIDI 3-1     '
client 30: 'Virtual Raw MIDI 3-2' [type=kernel,card=3]
    0 'VirMIDI 3-2     '
client 31: 'Virtual Raw MIDI 3-3' [type=kernel,card=3]
    0 'VirMIDI 3-3     '
client 32: 'H9 Pedal' [type=kernel,card=4]
    0 'H9 Pedal MIDI 1 '
        Connecting To: 129:0
        Connected From: 36:0, 129:0
client 36: 'ESI MIDIMATE eX' [type=kernel,card=5]
    0 'ESI MIDIMATE eX MIDI 1'
        Connecting To: 32:0, 40:0, 129:0
        Connected From: 129:0
    1 'ESI MIDIMATE eX MIDI 2'
client 40: 'GT-1000' [type=kernel,card=6]
    0 'GT-1000 MIDI 1  '
        Connecting To: 129:0
        Connected From: 36:0, 129:0
    1 'GT-1000 MIDI 2  '
client 129: 'Net Client' [type=user,pid=568]
    0 'Network         '
        Connecting To: 32:0, 36:0, 40:0
        Connected From: 32:0, 36:0, 40:0

My /etc/amidiauto.conf looks like this

[allow]  
ESI MIDIMATE eX -> H9 Pedal  
ESI MIDIMATE eX -> GT-1000  
ESI MIDIMATE eX <-> Net Client            
GT-1000 <-> Net Client
GT-1000 <-> midibri01blu
H9 Pedal <-> Net Client

Any way around this ?

**Comment by gtrainavicius** [comment]
Check out [amidiminder](https://community.blokas.io/t/amidiminder-utility/2243) utility which was inspired by amidiauto and supports indexed port mapping. Amidiminder will be preferred to amidiauto, as it already provides this feature.
